# Generated by Django 6.0 on 2026-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('svelte', 'Svelte'), ('nextjs', 'Next.js'), ('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('node', 'Node.js'), ('express', 'Express'), ('php', 'PHP'), ('laravel', 'Laravel'), ('ruby', 'Ruby'), ('rails', 'Ruby on Rails'), ('go', 'Go'), ('rust', 'Rust'), ('java', 'Java'), ('spring', 'Spring Boot'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('dot-net', '.NET'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('flutter', 'Flutter'), ('react-native', 'React Native'), ('sql', 'SQL'), ('shell', 'Shell/Bash'), ('unity', 'Unity'), ('unreal', 'Unreal Engine')], default='javascript', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
